export default {
    // A structured representation of the physical delivery address for the vCard object
    ADR: "",
    // Information about another person who will act on behalf of the vCard object. Typically this would be an area administrator, assistant, or secretary for the individual. Can be either a URL or an embedded vCard.
    AGENT: "",
    // Defines the person's anniversary.
    ANNIVERSARY: "",
    // Date of birth of the individual associated with the vCard.
    BDAY: "",
    // All vCards must start with this property.`,
    BEGIN: "",
    // A URL to use for sending a scheduling request to the person's calendar.`,
    CALADRURI: "",
    // A URL to the person's calendar.`,
    CALURI: "",
    // A list of "tags" that can be used to describe the object represented by this vCard.`,
    CATEGORIES: "",
    // Describes the sensitivity of the information in the vCard.`,
    CLASS: "",
    // Used for synchronizing different revisions of the same vCard.`,
    CLIENTPIDMAP: "",
    // The address for electronic mail communication with the vCard object.`,
    EMAIL: "",
    // All vCards must end with this property.`,
    END: "",
    // Defines a URL that shows when the person is "free" or "busy" on their calendar.`,
    FBURL: "",
    // The formatted name string associated with the vCard object.`,
    FN: "",
    // Defines the person's gender.`,
    GENDER: "",
    // Specifies a latitude and longitude.`,
    GEO: "",
    // Defines an instant messenger handle.\n\nThis property was introduced in a separate RFC when the latest vCard version was 3.0. Therefore, 3.0 vCards might use this property without otherwise declaring it.`,
    IMPP: "",
    // The public encryption key associated with the vCard object. It may point to an external URL, may be plain text, or may be embedded in the vCard as a Base64 encoded block of text.`,
    KEY: "",
    // Defines the type of entity that this vCard represents: 'application', 'individual', 'group', 'location' or 'organization'; 'x-*' values may be used for experimental purposes.[5][6]`,
    KIND: "",
    // Represents the actual text that should be put on the mailing label when delivering a physical package to the person/object associated with the vCard (related to the ADR property).\n\nNot supported in version 4.0. Instead, this information is stored in the LABEL parameter of the ADR property. Example: ADR;TYPE=home;LABEL="123 Main St\nNew York, NY 12345":;;123 Main St;New York;NY;12345;USA`,
    LABEL: "",
    // Defines a language that the person speaks.`,
    LANG: "",
    // An image or graphic of the logo of the organization that is associated with the individual to which the vCard belongs. It may point to an external URL or may be embedded in the vCard as a Base64 encoded block of text.`,
    LOGO: "",
    // Type of email program used.`,
    MAILER: "",
    // Defines a member that is part of the group that this vCard represents. Acceptable values include:\na "mailto:" URL containing an email address\na UID which references the member's own vCard\nThe KIND property must be set to "group" in order to use this property.`,
    MEMBER: "",
    // A structured representation of the name of the person, place or thing associated with the vCard object.`,
    N: "",
    // Provides a textual representation of the SOURCE property.`,
    NAME: "",
    // One or more descriptive/familiar names for the object represented by this vCard.`,
    NICKNAME: "",
    // Specifies supplemental information or a comment that is associated with the vCard.`,
    NOTE: "",
    // The name and optionally the unit(s) of the organization associated with the vCard object. This property is based on the X.520 Organization Name attribute and the X.520 Organization Unit attribute.`,
    ORG: "",
    // An image or photograph of the individual associated with the vCard. It may point to an external URL or may be embedded in the vCard as a Base64 encoded block of text.`,
    PHOTO: "",
    // The identifier for the product that created the vCard object.`,
    PRODID: "",
    // States that the vCard is a vCard.`,
    PROFILE: "",
    // Another entity that the person is related to. Acceptable values include:\na "mailto:" URL containing an email address\na UID which references the person's own vCard`,
    RELATED: "",
    // A timestamp for the last time the vCard was updated.`,
    REV: "",
    // The role, occupation, or business category of the vCard object within an organization.`,
    ROLE: "",
    // Defines a string that should be used when an application sorts this vCard in some way.\nNot supported in version 4.0. Instead, this information is stored in the SORT-AS parameter of the N and/or ORG properties.`,
    "SORT-STRING": "",
    // By default, if this property is not grouped with other properties it specifies the pronunciation of the FN property of the vCard object. It may point to an external URL or may be embedded in the vCard as a Base64 encoded block of text.`,
    SOUND: "",
    // A URL that can be used to get the latest version of this vCard.`,
    SOURCE: "",
    // The canonical number string for a telephone number for telephony communication with the vCard object.`,
    TEL: "",
    // Specifies the job title, functional position or function of the individual associated with the vCard object within an organization.`,
    TITLE: "",
    // The time zone of the vCard object.`,
    TZ: "",
    // Specifies a value that represents a persistent, globally unique identifier associated with the object.`,
    UID: "",
    // A URL pointing to a website that represents the person in some way.`,
    URL: "",
    // The version of the vCard specification. In version 4.0, this must come right after the BEGIN property.`,
    VERSION: "",
    // Any XML data that is attached to the vCard. This is used if the vCard was encoded in XML (xCard standard) and the XML document contained elements which are not part of the xCard standard.`,
    XML: "",

    uid: "",
    user: "",
    family: [],
    frequency: "",
    action: [],
    updates: [],
    last_udpate: null,
    next_contact: null,
    group: "",
    platform: "",
    status: false
}