name: test
on: 
  push:
      branches:
        - develop

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo Hello World! > hello-world.txt