name: Greeting from Mona
on: 
  push:
      branches:
        - develop

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      run: |
        echo testing